const API_URL = process.env.REACT_APP_API_URL;
const GOOGLE_CLIENT_ID = process.env.REACT_APP_GOOGLE_CLIENT_ID;
const DRF_CLIENT_ID = process.env.REACT_APP_DRF_CLIENT_ID;
const DRF_CLIENT_SECRET = process.env.REACT_APP_DRF_CLIENT_SECRET;

export { API_URL, GOOGLE_CLIENT_ID, DRF_CLIENT_ID, DRF_CLIENT_SECRET };
